export enum CONFIG_KEYS {
  APP_PORT = "APP_PORT",
  APP_HOST = "APP_HOST",
  DATABASE_HOST = "DATABASE_HOST",
  DATABASE_PORT = "DATABASE_PORT",
  DATABASE_NAME = "DATABASE_NAME",
  DATABASE_USERNAME = "DATABASE_USERNAME",
  DATABASE_PASSWORD = "DATABASE_PASSWORD",
  JWT_SECRET_KEY = "JWT_SECRET_KEY",
}